# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

include ${LAYERDIR}/include/openamp.inc

#MACHINE_FEATURES:append = " RZ_REMOTEPROC"
#MACHINE_FEATURES:append = " RZ_CM33_COLDBOOT"
#MACHINE_FEATURES:append = " RZ_CM33_FIRMWARE_LOAD"
#MACHINE_FEATURES:append = " RZ_SD2_SUPPORT"
#MACHINE_FEATURES:append = " RZ_JTAG_SUPPORT"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rz-multi-os"
BBFILE_PATTERN_rz-multi-os := "^${LAYERDIR}/"

LAYERDEPENDS_rz-multi-os = "meta-rz-bsp"
LAYERSERIES_COMPAT_rz-multi-os = "scarthgap"
